### ISSUE TITLE
Popper with transformed element

### ISSUE THREAD

**Issue by Johann-S** [FezVrasta/popper.js#202]
Hi @FezVrasta

I'm working to remove Tether dependency from Bootstrap (https://github.com/twbs/bootstrap/commits/v4-experimental-tooltip), and we have a unit test which check if the tooltip for a transformed element is correctly placed.
It seems it's not the case

### CodePen demo

http://codepen.io/Johann-S/pen/JNPBrY

### What is the expected behavior?

The `1` should be center

**Comment by FezVrasta** [comment]
Hi, unfortunately transformed elements support isn't supported quite well at the moment. Right now I'm working on some internal refactoring to fix higher properties bugs, but I'm open to PRs to improve support for this use case.

**Comment by FezVrasta** [comment]
To add some context, we already have [a failing test](https://github.com/FezVrasta/popper.js/pull/192) (disabled for now) to test the functionality (in at least one specific context).

**Comment by Johann-S** [comment]
I'll follow the development of Popper to know when this issue will be fixed 👍

**Comment by FezVrasta** [comment]
May I know why do you need to support this case? Is it that common?

**Comment by Johann-S** [comment]
It's a historical test introduced in _v3.3.0_ and if we choose Popper instead of Tether we have to ensure that everything will work the same way than before.


See the test : https://github.com/twbs/bootstrap/blob/v4-dev/js/tests/unit/tooltip.js#L734-L769

**Comment by FezVrasta** [comment]
I see, I was just curious to understand why is it so important to be inside the test suite. Maybe it's something that the Bootstrap's CSS itself makes use of or else. 🤔

**Comment by Johann-S** [comment]
No it's not in the Bootstrap's CSS itself, but it something folks use.

I've finished my work to integrate Popper to Bootstrap and everything work fine, but not this test 😢

**Comment by FezVrasta** [comment]
Right now I'm stuck on this problem:
https://github.com/FezVrasta/popper.js/pull/201#issuecomment-293559345

Any help to proceed in this direction will speed up the work needed to start working on #202.

**Comment by FezVrasta** [comment]
Your issue has been fixed, if the CI pass I expect to release a pre release, let you try it and then release a new version with the fix.

**Comment by Johann-S** [comment]
Nice ! Thank you @FezVrasta 

In my next PR for Bootstrap, Popper will be used for Tooltip, Popover and Dropdown

**Comment by FezVrasta** [comment]
Ok great!

Please install the latest pre release with `popper.js@next` and let me know if it works for you. I'll wait your reply to publish it as stable.

**Comment by Johann-S** [comment]
I updated my CodePen (http://codepen.io/Johann-S/pen/JNPBrY) but it seems better but not centered totally

**Comment by FezVrasta** [comment]
That's something I noticed happens only in CodePen, I'm not sure what happens there 🤔

**Comment by Johann-S** [comment]
Same not on CodePen : 

![image](https://cloud.githubusercontent.com/assets/1689750/25042605/c80ca5e4-2119-11e7-9445-e1f274074208.png)

**Comment by FezVrasta** [comment]
Ops, yes, looks like I fucked up the test. Sorry.

**Comment by FezVrasta** [comment]
So, I'm having some problems computing the scrollbar presence in transformed elements... If you have ideas please write them down here. The interested function is `getBoundingClientRect`.

**Comment by Johann-S** [comment]
I made a CodePen with an exemple of Tether on a transformed element : http://codepen.io/Johann-S/pen/GmgyYG

Maybe it can help you

**Comment by FezVrasta** [comment]
Thank you, unluckily it doesn't help because their logic is very basic and doesn't take in account a lot of variables. Btw I'm on it, expect a fix in few minutes.

**Comment by FezVrasta** [comment]
Please try `popper.js@1.5.1-pre`, again, on CodePen there's a small offset, but on my tests not (this time for real 🙂)

If you understand why CodePen behaves differently I can fix it.

**Comment by FezVrasta** [comment]
Update, figured out the problem. My tests live in a wrapping `div`, without it I get the same bug.

I'm working on it.

**Comment by Johann-S** [comment]
Seems better 👍 but a bit too much at the left (http://codepen.io/Johann-S/pen/JNPBrY)

**Comment by FezVrasta** [comment]
So, this is my test:
https://codepen.io/FezVrasta/pen/wdByGL?editors=0010

I don't get why here everything works fine, and in your codepen it doesn't..

**Comment by FezVrasta** [comment]
Fixed: https://codepen.io/FezVrasta/pen/oWgEpP

**Comment by FezVrasta** [comment]
You can use 1.5.1

**Comment by Johann-S** [comment]
Thank you @FezVrasta 👍 My test on Bootstrap still failed but what I see is much much better thanks to you

**Comment by FezVrasta** [comment]
Make sure it addresses decimal pixels, my tests use a custom `toBeApprox` assertion to make sure they don't fail if the position is just few decimals off.

**Comment by Johann-S** [comment]
Thank you I'll check that 👍 
Do you know when a minified version of `1.5.1` will be available ?

**Comment by FezVrasta** [comment]
It's already available:
https://unpkg.com/popper.js@1.5.1/dist/popper.min.js
https://unpkg.com/popper.js@1.5.1/dist/popper.es5.min.js
