### ISSUE TITLE
hide popper when it scrolls outside of its boundaries

### ISSUE THREAD

**Issue by andresgutgon** [FezVrasta/popper.js#52]
### What is the expected behavior?
I would expect popper to disappear when element is not visible

## Demo
![overflow](https://cloud.githubusercontent.com/assets/49499/15817609/244521d8-2bd9-11e6-9196-0efb5f813393.gif)

To reproduce this you just need to change height on `.example2__scroll-box` from `200%` to `10000px`
![image](https://cloud.githubusercontent.com/assets/49499/15817628/3c737688-2bd9-11e6-8f22-cef232c69692.png)

## Solution
I'll try to do something with a custom modifier. But I think this should be fixed in the core.

**Comment by FezVrasta** [comment]
Yes probably we should add a "hide when reference is not visible" modifier (maybe with a shorter name ahah).

If you create one please send a PR, it would be a nice addition!

**Comment by andresgutgon** [comment]
What is the best why to hide popper? I mean. With a modifier you just past `data` object modified. What should I pass to hide the popper?

**Comment by FezVrasta** [comment]
I think the `applyStyle` modifier should be edited a bit to allow custom CSS properties.

**Comment by andresgutgon** [comment]
Hi, I'm not sure I have time to do the PR now. But this is what I did:

I defined a modifier called `hideOnReferenceNotVisibleOnBoundaries` and if boundaries is defined check their visibility. Be aware that this code is jQuery dependent

``` javascript
      /**
       * Check if reference is visible inside boundaries
       *
       * @param {Object} data
       * @param {Object} boundariesElement
       * @return {Boolean}
       */
      function isVisible(data, boundariesElement) {
        const { boundaries, offsets } = data;
        const { top, bottom } = offsets.reference;
        const { height: boundariesHeight} = boundaries;
        const boundariesOffsetTop = $(boundariesElement).offset().top;
        const boundariesBottom = boundariesOffsetTop + boundariesHeight;

        return ((top <= boundariesBottom) && (bottom >= boundariesOffsetTop));
      }

      /**
       * Modifier to hide popper if is outside boundaries
       * If boundaries is not defined we skip the check
       *
       * @param {Object} data
       * @return {Object}
       */
      const hideOnReferenceNotVisibleOnBoundaries = (data) => {
        const boundariesElement = data.instance._options.boundariesElement;

        if (boundariesElement === 'viewport') return data;

        const visible = isVisible(data, boundariesElement);

        // Hide popper
        $(data.instance._popper).toggleClass('js-hide', !visible);

        return data;
      };

```

**Comment by FezVrasta** [comment]
That's a bit too hacky to be included in Popper.js... Thanks anyway for your attempt. If someone else is interested please let me know. I can help with it.

**Comment by andresgutgon** [comment]
What's the hacky part? Just to improve my version :)

**Comment by FezVrasta** [comment]
We don't use jQuery with Popper.js, and modifiers should never access the DOM to write to it in any way.

Your modifier should edit only the `data` object, adding maybe a `data.hidden` property, then, `applyStyle` modifier should read the value and then hide or not the popper.

**Comment by andresgutgon** [comment]
Ok, thanks @FezVrasta

**Comment by FezVrasta** [comment]
@andresgutgon check out #53, it should help with this modifier.

**Comment by andresgutgon** [comment]
I think we can close this one

**Comment by FezVrasta** [comment]
Why? The enhancement is not implemented yet

**Comment by andresgutgon** [comment]
I thought is a user decision to implement that. That you only provide the `styles` in data to change visibility.

Of you want this modifier/whatever be in the core?

**Comment by FezVrasta** [comment]
I think it's a feature that would be nice to have in the core.

**Comment by FezVrasta** [comment]
I've implemented this feature in the `v1-dev` branch, if someone wants to backport it to the `v0` version please use the modifier below and include it before the `applyStyles` modifier:

```js
function hide(data) {
    const refRect = data.offsets.reference;
    const bound = data.boundaries;

    if (
        refRect.bottom < bound.top ||
        refRect.left > bound.right ||
        refRect.top > bound.bottom ||
        refRect.right < bound.left
    ) {
        data.styles.display = 'none';
    } else {
        data.styles.display = '';
    }

    return data;
}
```

**Comment by ericsakmar** [comment]
Is this still the best way to handle this situation? Thanks!

**Comment by ericsakmar** [comment]
I'm still seeing the popover after it scrolls outside of the boundaries. Is there anything I need to do to enable this feature?

**Comment by FezVrasta** [comment]
You have to enable it, it's disabled by default

**Comment by ericsakmar** [comment]
Cool. How would I enable it? I'm not quite sure I understand. Thanks!

**Comment by FezVrasta** [comment]
```
new Popper(ref, pop, {
  modifiers: {
    hide: { enabled: true }
  }
})
```

**Comment by atomiks** [comment]
@FezVrasta `hide` is enabled by default isn't it? 😆 

https://popper.js.org/popper-documentation.html#modifiers..hide.enabled

@ericsakmar  you need to use something like

```css
.popper[x-out-of-boundaries] {
  display: none;
}
```

**Comment by FezVrasta** [comment]
oh, right, thanks

**Comment by larsbo** [comment]
is this really working?
I use Popper.js 1.15.0 and my popper containers never gets the `x-out-of-boundaries` attribute when they are not inside the viewport.

**Comment by nmanikumar5** [comment]
Its not working properly @FezVrasta

**Comment by JLiu1272** [comment]
Hi, @FezVrasta, I tried using the modifier you suggested, and like @nmanikumar5, I am not able to get it to work either.

**Comment by dparker2** [comment]
For future readers, this is exactly what I added to get this to work (with v2 of popper):
```
  &[data-popper-reference-hidden='true'] {
    opacity: 0;
    pointer-events: none;
  }
```

I found that `opacity` worked better than `visibility`, which was causing a weird lag for some reason. The docs also don't include the `='true'` part in the selector even though that's needed here, since the attribute changes to `false` instead of actually being removed when the reference is in view.

**Comment by mdxiaohu** [comment]
> For future readers, this is exactly what I added to get this to work (with v2 of popper):对于未来的读者，这正是我添加的内容（使用 popper v2）：
> 
> ```
>   &[data-popper-reference-hidden='true'] {
>     opacity: 0;
>     pointer-events: none;
>   }
> ```
> 
> I found that `opacity` worked better than `visibility`, which was causing a weird lag for some reason. The docs also don't include the `='true'` part in the selector even though that's needed here, since the attribute changes to `false` instead of actually being removed when the reference is in view.我发现`opacity`比`visibility`效果更好，这由于某种原因导致了奇怪的滞后。即使此处需要，文档也不在选择器中包含`='true'`部分，因为当引用处于视图中时，属性会更改为`false`而不是实际删除。
Combining the two together will yield better results .
`&[data-popper-reference-hidden='true'] {
    visibility: hidden;
    opacity: 0;
    pointer-events: none;
  }`
This can prevent the height of the page from being affected.

**Comment by mdxiaohu** [comment]
> For future readers, this is exactly what I added to get this to work (with v2 of popper):对于未来的读者，这正是我添加的内容（使用 popper v2）：
> 
> ```
>   &[data-popper-reference-hidden='true'] {
>     opacity: 0;
>     pointer-events: none;
>   }
> ```
> 
> I found that `opacity` worked better than `visibility`, which was causing a weird lag for some reason. The docs also don't include the `='true'` part in the selector even though that's needed here, since the attribute changes to `false` instead of actually being removed when the reference is in view.我发现`opacity`比`visibility`效果更好，这由于某种原因导致了奇怪的滞后。即使此处需要，文档也不在选择器中包含`='true'`部分，因为当引用处于视图中时，属性会更改为`false`而不是实际删除。



> For future readers, this is exactly what I added to get this to work (with v2 of popper):
> 
> ```
>   &[data-popper-reference-hidden='true'] {
>     opacity: 0;
>     pointer-events: none;
>   }
> ```
> 
> I found that `opacity` worked better than `visibility`, which was causing a weird lag for some reason. The docs also don't include the `='true'` part in the selector even though that's needed here, since the attribute changes to `false` instead of actually being removed when the reference is in view.

At present,
Combining the two together will yield better results .
```
&[data-popper-reference-hidden='true'] {
    visibility: hidden;
    opacity: 0;
    pointer-events: none;
 }
```
This can prevent the height of the page from being affected.

**Comment by mdxiaohu** [comment]
> For future readers, this is exactly what I added to get this to work (with v2 of popper):
> 
> ```
>   &[data-popper-reference-hidden='true'] {
>     opacity: 0;
>     pointer-events: none;
>   }
> ```
> 
> I found that `opacity` worked better than `visibility`, which was causing a weird lag for some reason. The docs also don't include the `='true'` part in the selector even though that's needed here, since the attribute changes to `false` instead of actually being removed when the reference is in view.

At present,
Combining the two together will yield better results .
```
&[data-popper-reference-hidden='true'] {
    visibility: hidden;
    opacity: 0;
    pointer-events: none;
 }
```
This can prevent the height of the page from being affected.
